export interface ModalState {
	isLoading: boolean
	isLoaded: boolean
	isFailed: boolean
	error: null | string
}

export enum ModalActionsTokens {
	COMPLITING_MODAL_HANDLER_INFO_ACTION = 'COMPLITING_MODAL_HANDLER_INFO_ACTION',
	COMPLITED_MODAL_HANDLER_INFO_ACTION = 'COMPLITED_MODAL_HANDLER_INFO_ACTION',
	ERROR_IN_COMPLITING_MODAL_HANDLER_INFO_ACTION = 'ERROR_IN_COMPLITING_MODAL_HANDLER_INFO_ACTION',

	CLEAR_MODAL_STATE_ACTION = 'CLEAR_MODAL_STATE_ACTION',
	ASYNC_MODAL_HANDLE_ACTION = 'ASYNC_MODAL_HANDLE_ACTION'
}
