export interface TechnologiesFilters {
	title: string
}

export interface ITechnologie {
	id: number
	name: string
	type: string
}

export interface ITechnologieType {
	id: number
	name: string
	technologies: Array<ITechnologie>
}

export interface TechnologiesState {
	data: Array<ITechnologieType>
	_data: Array<ITechnologieType>
	filters: TechnologiesFilters
	isLoading: boolean
	isLoaded: boolean
	isFailed: boolean
	error: null | string
}

export enum TechnologiesActionsTokens {
	LOADING_TECHNOLOGIES_INFO_ACTION = 'LOADING_TECHNOLOGIES_INFO_ACTION',
	LOADED_TECHNOLOGIES_INFO_ACTION = 'LOADED_TECHNOLOGIES_INFO_ACTION',
	ERROR_IN_LOADING_TECHNOLOGIES_INFO_ACTION = 'ERROR_IN_LOADING_TECHNOLOGIES_INFO_ACTION',
	CHANGE_TECHNOLOGIES_FILTERS_ACTION = 'CHANGE_TECHNOLOGIES_FILTERS_ACTION',

	NEW_TECHNOLOGIE_CREATED_ACTION = 'NEW_TECHNOLOGIE_CREATED_ACTION',
	NEW_TECHNOLOGIE_GROUP_CREATED_ACTION = 'NEW_TECHNOLOGIE_GROUP_CREATED_ACTION',

	EDITED_TECHNOLOGIE_TYPE_INFO_ACTION = 'EDITED_TECHNOLOGIE_TYPE_INFO_ACTION',
	DELETED_TECHTYPE_INFO_ACTION = 'DELETED_TECHTYPE_INFO_ACTION',

	EDITED_TECHNOLOGIE_INFO_ACTION = 'EDITED_TECHNOLOGIE_INFO_ACTION',
	DELETED_TECHNOLOGIE_INFO_ACTION = 'DELETED_TECHNOLOGIE_INFO_ACTION',

	ASYNC_LOAD_TECHNOLOGIES_INFO_ACTION = 'ASYNC_LOAD_TECHNOLOGIES_INFO_ACTION'
}
