from .agent_base import AgentBase
from uuid import uuid4
from requests import post

class CVAgent(AgentBase):
  def __init__(self):
    super().__init__()

  def execute(self, input_dict: dict) -> str:
    user_id = input_dict["user_id"]
    name = uuid4().hex
    post(f"http://localhost:3000/api/doc/create/{user_id}", json={
      "title": name,
      "description": "CV generated by BOT"
    })

    return f"Я сохранил резюме под именем: {name}!", {}, {}

    
