export interface IProfessionalSkill {
	id: number
	last: number
	total: number
}

export interface ProfessionalSkillsState {
	data: Array<IProfessionalSkill>
	isLoading: boolean
	isLoaded: boolean
	isFailed: boolean
	error: null | string
}

export enum ProfessionalSkillsActionsTokens {
	LOADING_PROFESSIONAL_SKILL_INFO_ACTION = 'LOADING_PROFESSIONAL_SKILL_INFO_ACTION',
	LOADED_PROFESSIONAL_SKILL_INFO_ACTION = 'LOADED_PROFESSIONAL_SKILL_INFO_ACTION',
	ERROR_IN_LOADING_PROFESSIONAL_SKILL_INFO_ACTION = 'ERROR_IN_LOADING_PROFESSIONAL_SKILL_INFO_ACTION',
	CHANGE_PROFESSIONAL_SKILL_FILTERS_ACTION = 'CHANGE_PROFESSIONAL_SKILL_FILTERS_ACTION',

	NEW_CV_CREATED_ACTION = 'NEW_CV_CREATED_ACTION',

	DELETED_CV_INFO_ACTION = 'DELETED_CV_INFO_ACTION',

	ASYNC_LOAD_PROFESSIONAL_SKILL_INFO_ACTION = 'ASYNC_LOAD_PROFESSIONAL_SKILL_INFO_ACTION'
}
